events {
    worker_connections 1024;
}

http {
    limit_req_zone $binary_remote_addr zone=query_limit:10m rate=20r/m;
    server {
        listen 1234;

        location /api {
            proxy_pass https://markuswiki.netlify.app/api;
            # proxy_set_header Origin https://netlify.app;
            proxy_set_header Referer https://netlify.app;
            proxy_set_header Host markuswiki.netlify.app;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_ssl_server_name on;
            proxy_ssl_protocols TLSv1.2 TLSv1.3;

            limit_req zone=query_limit burst=1;
            limit_req_status 429;

            error_page 429 = /rate-limiting.html;
        }

        location = /rate-limiting.html {
            root /home/marcus/projects/nckh2627/rag-chatbot-be/static;
            internal;
        }
    }
}